name: ArduPilot Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ArduPilot
        uses: actions/checkout@v4
        with:
          repository: ArduPilot/ardupilot
          submodules: recursive
          ref: master

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi python3-dev libpython3-dev python3-pip
          python3 -m pip install empy==3.3.4 pyserial

      - name: Build
        run: |
          # Конфігурація та збірка
          python3 waf configure --board MatekF405-WING
          python3 waf build

      - name: List files (Debug)
        run: |
          # Це допоможе нам побачити, де саме лежить файл, якщо він не з'явиться в артефактах
          find build -name "*.bin"
          find build -name "*.apj"

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-files
          path: build/**/bin/*
